# Generated by Django 2.1.7 on 2019-03-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20190322_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtosub_mapping',
            unique_together={('ClassId', 'SubId')},
        ),
        migrations.AlterUniqueTogether(
            name='cumulativeattendance',
            unique_together={('RollNo', 'SubId')},
        ),
        migrations.AlterUniqueTogether(
            name='cumulativeattendancetotal',
            unique_together={('ClassId', 'SubId')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('RollNo', 'Date_c', 'SubId')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancetotal',
            unique_together={('ClassId', 'Date_c', 'SubId')},
        ),
        migrations.AlterUniqueTogether(
            name='proftosubmapping',
            unique_together={('ClassId', 'RollNo', 'Prof')},
        ),
    ]
