# Generated by Django 2.1.7 on 2019-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190322_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='electiveMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElecId', models.CharField(max_length=10)),
                ('Prof', models.CharField(max_length=100)),
                ('ClassId', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='electivemapping',
            unique_together={('ClassId', 'ElecId', 'Prof')},
        ),
    ]
