# Generated by Django 2.0.1 on 2019-03-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190308_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profToSub',
        ),
    ]
